apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  labels:
    app.kubernetes.io/name: apps-of-apps
    app.kubernetes.io/part-of: argocd-production
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: production/
    repoURL: 'https://github.com/slamer59/dagster-argocd-configuration.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
