apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    name: ''
    namespace: dagster
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/dagster
    repoURL: 'https://github.com/slamer59/dagster-argocd-configuration.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
