apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dagster
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: dagster
    server: 'https://kubernetes.default.svc'
  source:
    path: helm/dagster
    repoURL: 'https://github.com/dagster-io/dagster'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
