apiVersion: v2
name: jupytherhub-argo
description: jupyterhub Helm Chart for ArgoCD

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: jupyterhub
  version: "1.1.3-n283.h7ffa01a9"
  repository: "https://jupyterhub.github.io/helm-chart/"
# - name: jupyterlab
#   version: "0.1.36"
#   repository: "https://maastrichtu-ids.github.io/dsri-helm-charts/"