# This file can update the JupyterHub Helm chart's default configuration values.
############################################################"
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
############################################################""

singleuser:
  defaultUrl: "/lab"
  extraEnv:
    - JUPYTERHUB_SINGLEUSER_APP: "jupyter_server.serverapp.ServerApp"
    - EDITOR: "vim"
  profileList:
    - display_name: "Small: default"
      description: |
        A small job. 1 CPU, no GPU. This is the default.
      default: True
      kubespawner_override:
        cpu_limit: 2
        cpu_guarantee: 1
        mem_limit: "16G"
        mem_guarantee: "512M"
        extra_resource_limits: {}
  image:
    # You should replace the "latest" tag with a fixed version from:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
    name: jupyter/minimal-notebook
    tag: python-3.9.7    
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            cp -r /tmp/environment.yaml /home/jovyan;

config:
  jupyterhub:
    cull:
      # Cull after 30min of inactivity
      every: 300
      timeout: 1800
      # No pods over 12h long
      maxAge: 43200