dagit:
  replicaCount: 1
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/dagster-celery-k8s"
    tag: 0.13.13
    pullPolicy: Always
  workspace:
    enabled: false
    servers:
      - host: "k8s-example-user-code-1"
        port: 3030
        name: "user-code-example"
dagster-user-deployments:
  enabled: true
  enableSubchart: true
  deployments:
    - name: "k8s-example-user-code-1"
      image:
        # When a tag is not supplied, it will default as the Helm chart version.
        repository: "docker.io/dagster/user-code-example"
        tag: 0.13.13
        pullPolicy: Always

      # Arguments to `dagster api grpc`.
      dagsterApiGrpcArgs:
        - "--python-file"
        - "/example_project/example_repo/repo.py"
      port: 3030
####################################################################################################
# Pipeline Run: Configuration for user code containers.
#
# `DAGSTER_K8S_PIPELINE_RUN_IMAGE` environment variable will point to the image specified below.
# The run config for the celery executor can set `job_image` to fetch from environment variable
# `DAGSTER_K8S_PIPELINE_RUN_IMAGE`, so that celery workers will launch k8s jobs with said image.
#
####################################################################################################
pipelineRun:
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/user-code-example"
    tag: 0.13.13
    pullPolicy: Always
scheduler:
  type: DagsterDaemonScheduler
  config: {}
runLauncher:
  type: K8sRunLauncher
  config:
    celeryK8sRunLauncher:
      image:
        repository: docker.io/dagster/dagster-celery-k8s
        tag: 0.13.13
        pullPolicy: Always
dagsterDaemon:
  image:
    # When a tag is not supplied for a Dagster provided image,
    # it will default as the Helm chart version.
    repository: "docker.io/dagster/dagster-celery-k8s"
    tag: 0.13.13
    pullPolicy: Always
